import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Epilogue } from 'next/font/google'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const epilogue = Epilogue({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={epilogue.className}
        data-theme="fantasy"
      >
        {children}
      </body>
    </html>
  );
}
