import type { Metadata } from "next";
import "./globals.css";
import { Epilogue } from 'next/font/google'

export const epilogue = Epilogue({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={epilogue.className}
        data-theme="fantasy"
      >
        {children}
      </body>
    </html>
  );
}
